### ISSUE TITLE
Stable diffusion support 

### ISSUE THREAD

**Issue by steventkrawczyk** [hegelai/prompttools#74]
### 🚀 The feature

We should look into experiments and eval functions for image models, like stable diffusion 

### Motivation, pitch

Many GenAI apps are multi modal, and we'll have to support more than LLMs in the long term

**Comment by HashemAlsaket** [comment]
Super cool. @steventkrawczyk , @NivekT mind assigning me? Current thought process is to build the experiment to measure against basic metrics like `Peak signal-to-noise ratio`, `Structural Similarity Index`, `Signal to reconstruction error ratio`. I think we may need to carve out a separate experiment class for image comparison (possibly a third for video comparison as well?) since the current experiment class is built to handle text with heavy support for dataframes.

**Comment by NivekT** [comment]
Sure, feel free to start on that. If anyone else has a different idea, please feel free to comment here as well.

Thanks @HashemAlsaket !
